### ISSUE TITLE
[High] L'application ne fonctionne pas sous IE dans la version utilisée par Continental

### ISSUE THREAD

**Issue by matthieulaheux** [WildCodeSchool/toulouse-0918-js-mycontribution#113]
![version-ie](https://user-images.githubusercontent.com/46710932/51821097-422c7180-22d8-11e9-9552-279ec41e7652.PNG)

**Comment by bhubr** [comment]
Je viens de pousser sur la brancher `master` un correctif. N'ayant pas d'ordi Windows sous la main, j'ai mis à jour l'instance de test et l'ai testée via un outil en ligne qui permet de tester des sites sous IE11. Cela semble fonctionner.

**Comment by matthieulaheux** [comment]
Je confirme, ça s'affiche!
Merci

**Comment by bhubr** [comment]
Parfait !

**Comment by bhubr** [comment]
Un premier commentaire sur la partie "support JavaScript" pour IE11, je mets des liens (techniques !) pour référence (l'erreur que tu avais dans la console pendant le partage d'écran ressemblait à ça).

Il faudra
1. de votre côté, vérifier si les IE tournent par défaut en mode "compatibilité" (avec une ancienne version)
2. du mien, ajouter des "polyfills" (librairies ajoutant des fonctionnalités de l'API JavaScript standard, aux navigateurs ne les supportant que partiellement ou pas du tout).

* https://github.com/facebook/create-react-app/issues/4255
* https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by bhubr** [comment]
Un deuxième sur la partie "support des polices de caractère". La disparition des icônes sous IE11 est un pb connu et référencé dans le bug tracker du bundle de fonts qu'on utilise, ainsi que des pistes (possiblement des restrictions, par défaut, sur le download de fonts "untrusted"... mais quid du côté  aléatoire 🤔 ).

* https://github.com/FortAwesome/Font-Awesome/issues/8825
* https://docs.microsoft.com/fr-fr/windows/security/threat-protection/block-untrusted-fonts-in-enterprise#Turn_on_and_use_the_Blocking_untrusted_fonts_feature
