### ISSUE TITLE
[Medium] L'icône "Edit" en haut à droite des initiatives/missions est toujours visible, mais non cliquable

### ISSUE THREAD

**Issue by matthieulaheux** [WildCodeSchool/toulouse-0918-js-mycontribution#115]
![editmission](https://user-images.githubusercontent.com/46710932/51821429-75233500-22d9-11e9-8989-e5f48ac4f11e.PNG)

**Comment by bhubr** [comment]
Fait dans le dernier lot d'updates poussé ce matin-même sur le serveur de test
