### ISSUE TITLE
[Highest] Short description non visible

### ISSUE THREAD

**Issue by matthieulaheux** [WildCodeSchool/toulouse-0918-js-mycontribution#122]
Lorsque l'on créé une initiative, la short description n'est jamais affichée.
Elle devrait être affichée:
- dans la fiche de l'initiative (style à définir, mais différent de la long description)
- sous l'expander dans la page d'aggrégation

**Comment by bhubr** [comment]
J'ai fait un "quick fix". Pour différencier le summary de la description longue dans la page projet, j'ai eu deux approches différentes suivant qu'on est:
- sur la liste des initiatives: j'ai bien lu que tu voulais la voir sous l'expander, mais sous fond uni ça me semblait difficile. Du coup je l'ai mis visible par défaut (après tout un summary, s'il est court, peut donner le minimum d'infos qui donne envie de cliquer)
- sur les détails d'un projet: je l'ai mis en italique, centré, en gris foncé, sous le titre du projet

Note, j'ai ajouté ce summary sur les items de la liste des *initiatives* mais pas des *missions*. En revanche, les deux utilisant le même composant pour afficher les détails, le summary s'affiche sur cette page indépendamment du type initiative ou mission.

Dites-moi assez vite si ça vous convient, et si non, des indications précises sur ce que vous souhaitez voir à la place (je suis en train de mettre à jour le build sur mon serveur, ça sera dispo dans la minute)

**Comment by matthieulaheux** [comment]
C'est parfait, à généraliser sur les missions
